Support CUDA 11.5
cupy/cupy-release-tools pull request #197
Opened 2021-11-04 05:35 UTC by takagi

2021-11-04 05:38 UTC, takagi commented
Images are not ready.

2021-11-04 05:40 UTC, takagi commented on dist_config.py
> +    'verify_image': 'nvidia/cuda:11.5.0-devel-{system}',
I can see no CUDA 11.5 image contains cuDNN and NCCL for now in https://gitlab.com/nvidia/container-images/cuda

2021-11-05 04:27 UTC, kmaehashi requested changes

2021-11-05 04:27 UTC, kmaehashi commented on dist_config.py
> +    'verify_image': 'nvidia/cuda:11.5.0-devel-{system}',
I think we can keep verification image as-is (continue using CUDA 11.4).

2021-11-05 04:27 UTC, kmaehashi commented on dist_config.py
> +        'image': 'nvidia/cuda:11.5.0-devel-centos7',
I've pushed the docker image `cupy/cupy-release-tools:cuda-runfile-11.5.0-centos7` built by `cuda-runfile/build.sh`. Could you use this image instead?

2021-11-05 04:27 UTC, kmaehashi commented on dist_config.py
> +        'verify_image': 'nvidia/cuda:11.5.0-runtime-{system}',
ditto

2021-11-05 04:27 UTC, kmaehashi commented
Just installed CUDA 11.5 on FlexCI Windows image.
/test

2021-11-06 06:14 UTC, kmaehashi commented
/test

2021-11-06 06:14 UTC, kmaehashi approved these changes

2021-11-07 14:59 UTC, kmaehashi commented
/test

2021-11-08 02:06 UTC, merged